---
name: Build, test and push docker image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "45 03 * * 0"

jobs:
  test:
    name: Test docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t docker-ansible-image .

      - name: Run docker image
        run: >-
          docker container run
          --name docker-ansible-container
          --cgroupns host
          --detach
          --privileged
          --volume /sys/fs/cgroup:/sys/fs/cgroup:rw
          docker-ansible-image

      - name: Ensure that ansible is working from within the docker image
        run: >-
          docker container exec
          --tty
          docker-ansible-container env TERM=xterm ansible --version

  release:
    name: Release docker image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.repository }}:latest
